FROM arm32v7/debian:bookworm

ENV TARGET=rpi
ENV DISTRO=bookworm

COPY scripts/install-base-deps.sh /opt/scripts/
RUN /opt/scripts/install-base-deps.sh && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*

COPY scripts/git-archive-all.sh /opt/scripts/
COPY scripts/build-package.sh /opt/scripts/

VOLUME "/out"
ENTRYPOINT [ "/bin/bash", "-c", "/opt/scripts/build-package.sh" ]
